version: '3'
services:
  web:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
  api:
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5500:5500
    volumes:
      - ./server:/app
      - /app/node_modules
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local
