version: '3'
services:
  web:
    image: mailnophone03/uet-review-frontend
    ports:
      - 3000:80
    depends_on:
      - api
  api:
    image: mailnophone03/uet-review-backend
    ports:
      - 5500:5500
    env_file: ./server/.env
