version: '3'
services:
  web:
    image: mailnophone03/uet-review-frontend
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=$REACT_APP_API_URL
  api:
    image: mailnophone03/uet-review-backend
    ports:
      - 5500:5500
    environment:
      - PORT=$PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
  mongodb:
    image: mongo
    restart: always
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
