version: 2.1
orbs:
  docker: circleci/docker@1.4.0

jobs:
  build_frontend:
    working_directory: ~/uet-review
    environment:
      DOCKER_IMAGE: mailnophone03/uet-review-frontend
      DOCKER_TAG: latest
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            cd ~/uet-review/client && docker build \
            --build-arg REACT_APP_API_URL=${REACT_APP_API_URL} \
            --build-arg REACT_APP_SOCKET_URL=${REACT_APP_SOCKET_URL} \
            -t $DOCKER_IMAGE:$DOCKER_TAG .
      - run:
          name: Push image to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE:$DOCKER_TAG
  build_backend:
    working_directory: ~/uet-review
    environment:
      DOCKER_IMAGE: mailnophone03/uet-review-backend
      DOCKER_TAG: latest
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            cd ~/uet-review/server && docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
      - run:
          name: Push image to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE:$DOCKER_TAG
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT
      - run: ssh -oStrictHostKeyChecking=no $DEPLOYED_USER@$DEPLOYED_SERVER 'cd ~/uet-review && sh ./deploy.sh'

workflows:
  my-pipeline:
    jobs:
      - build_frontend
      - build_backend
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - build_frontend
            - build_backend
