FROM node:18-alpine as builder

ENV PORT=5500

RUN mkdir /app

WORKDIR /app

COPY ./package.json .
COPY ./yarn.lock .

RUN yarn global add typescript && yarn

COPY . .

CMD ["yarn", "dev"]
EXPOSE 5500

